# Add 'repo' label to any root file changes
repo:
  - '*'

# Add apps label to any change within the 'apps' folder
apps:
  - apps/*

# Add 'test' label to any change to *.spec.js files within the source dir
test:
  - ['apps/**/*.spec.js', 'apps/**/*.spec.ts', 'apps/**/*.spec.tsx']
  - ['libs/**/*.spec.js', 'libs/**/*.spec.ts', 'libs/**/*.spec.tsx']

# Add 'source' label to any change to src files within the source dir EXCEPT for the docs sub-folder
source:
  - any: ['**/src/**/*']

# Add 'config` label to any change to *.json files
config:
  - any: ['src/**/*.json']
